[package]
name = "trident-idl-spec"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
syn = { version = "2", features = ["visit", "full"] }
quote = "1"
